sequenceDiagram
    User->>+Browser: Text input
    note right of Browser: pressing the "save" button
    Browser->>+Server: POST https://studies.cs.helsinki.fi/exampleapp/new_note { "content": "some text", "date": "someday" }

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate Server
    Server-->>Browser: HTML document
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate Server
    Server-->>Browser: the css file
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate Server
    Server-->>Browser: the JavaScript file
    deactivate Server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate Server
    Server-->>Browser: [{ "content": "note content", "date": "someday" }, ... ]
    deactivate Server


